=== apache/struts/core/src/main/resources/xwork-2.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- START SNIPPET: xworkDtd -->

<!--
   XWork configuration DTD.
   Use the following DOCTYPE
   
   <!DOCTYPE xwork PUBLIC 
	"-//Apache Struts//XWork 2.0//EN"
	"http://struts.apache.org/dtds/xwork-2.0.dtd">
-->

<!ELEMENT xwork (package|include|bean|constant)*>

<!ELEMENT package (result-types?, interceptors?, default-interceptor-ref?, default-action-ref?, default-class-ref?, global-results?, global-exception-mappings?, action*)>
<!ATTLIST package
    name CDATA #REQUIRED
    extends CDATA #IMPLIED
    namespace CDATA #IMPLIED
    abstract CDATA #IMPLIED
>

<!ELEMENT result-types (result-type+)>

<!ELEMENT result-type (param*)>
<!ATTLIST result-type
    name CDATA #REQUIRED
    class CDATA #REQUIRED
    default (true|false) "false"
>

<!ELEMENT interceptors (interceptor|interceptor-stack)+>

<!ELEMENT interceptor (param*)>
<!ATTLIST interceptor
    name CDATA #REQUIRED
    class CDATA #REQUIRED
>

<!ELEMENT interceptor-stack (interceptor-ref*)>
<!ATTLIST interceptor-stack
    name CDATA #REQUIRED
>

<!ELEMENT interceptor-ref (param*)>
<!ATTLIST interceptor-ref
    name CDATA #REQUIRED
>

<!ELEMENT default-interceptor-ref (#PCDATA)>
<!ATTLIST default-interceptor-ref
    name CDATA #REQUIRED
>

<!ELEMENT default-action-ref (#PCDATA)>
<!ATTLIST default-action-ref
    name CDATA #REQUIRED
>

<!ELEMENT default-class-ref (#PCDATA)>
<!ATTLIST default-class-ref
   class CDATA #REQUIRED
>

<!ELEMENT global-results (result+)>

<!ELEMENT global-exception-mappings (exception-mapping+)>

<!ELEMENT action (param|result|interceptor-ref|exception-mapping)*>
<!ATTLIST action
    name CDATA #REQUIRED
    class CDATA #IMPLIED
    method CDATA #IMPLIED
    converter CDATA #IMPLIED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #REQUIRED
>

<!ELEMENT result (#PCDATA|param)*>
<!ATTLIST result
    name CDATA #IMPLIED
    type CDATA #IMPLIED
>

<!ELEMENT exception-mapping (#PCDATA|param)*>
<!ATTLIST exception-mapping
    name CDATA #IMPLIED
    exception CDATA #REQUIRED
    result CDATA #REQUIRED
>

<!ELEMENT include (#PCDATA)>
<!ATTLIST include
    file CDATA #REQUIRED
>

<!ELEMENT bean (#PCDATA)>
<!ATTLIST bean
    type CDATA #IMPLIED
    name CDATA #IMPLIED
    class CDATA #REQUIRED
    scope CDATA #IMPLIED
    static CDATA #IMPLIED
    optional CDATA #IMPLIED
>

<!ELEMENT constant (#PCDATA)>
<!ATTLIST constant
    name CDATA #REQUIRED
    value CDATA #REQUIRED    
>

<!-- END SNIPPET: xworkDtd -->

=== apache/struts/plugins/oval/src/test/resources/oval-test.xml
<!DOCTYPE xwork PUBLIC
        "-//Apache Struts//XWork 2.0//EN"
        "http://struts.apache.org/dtds/xwork-2.0.dtd"
        >

<xwork>
    <bean type="org.apache.struts2.oval.interceptor.OValValidationManager" class="org.apache.struts2.oval.interceptor.DummyDefaultOValValidationManager"/>
    <constant name="struts.enable.SlashesInActionNames" value="true"/>
    <constant name="struts.oval.validateJPAAnnotations" value="false" />

    <package namespace="oval" name="oval-test">
        <result-types>
            <result-type name="void" class="org.apache.struts2.oval.interceptor.VoidResult"/>
        </result-types>
        <interceptors>
            <interceptor name="ovalValidation" class="org.apache.struts2.oval.interceptor.OValValidationInterceptor"/>
        </interceptors>

        <action name="simpleFieldsJPA" class="org.apache.struts2.oval.interceptor.SimpleFieldJPAAnnotations">
            <interceptor-ref name="ovalValidation">
                <param name="validateJPAAnnotations">true</param>
            </interceptor-ref>
            <result type="void"></result>
        </action>
        <action name="simpleFieldsXMLChild" class="org.apache.struts2.oval.interceptor.SimpleFieldsXMLChild">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="validationInMethods" class="org.apache.struts2.oval.interceptor.ValidationInMethods">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldsXML/*" class="org.apache.struts2.oval.interceptor.SimpleFieldsXML">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldsXML" class="org.apache.struts2.oval.interceptor.SimpleFieldsXML">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldsXMLCaching" class="org.apache.struts2.oval.interceptor.SimpleFieldsXML">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleField" class="org.apache.struts2.oval.interceptor.SimpleField">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldTooLong" class="org.apache.struts2.oval.interceptor.SimpleField">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleMethod" class="org.apache.struts2.oval.interceptor.SimpleMethod">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldOGNL" class="org.apache.struts2.oval.interceptor.SimpleFieldOGNLExpression">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldI18n" class="org.apache.struts2.oval.interceptor.SimpleFieldI18n">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldI18nDefaultKey" class="org.apache.struts2.oval.interceptor.SimpleFieldI18nDefaultKey">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="fieldsWidthProfiles13" class="org.apache.struts2.oval.interceptor.FieldsWithProfiles" method="run1">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="fieldsWidthProfiles2" class="org.apache.struts2.oval.interceptor.FieldsWithProfiles" method="run2">
            <interceptor-ref name="ovalValidation"/>
            <result type="void"></result>
        </action>
        <action name="simpleFieldNoValidate" class="org.apache.struts2.oval.interceptor.SimpleField">
            <interceptor-ref name="ovalValidation">
                <param name="alwaysInvokeValidate">false</param>
            </interceptor-ref>
            <result type="void"></result>
        </action>
        <action name="simpleFieldNoProgrammatic" class="org.apache.struts2.oval.interceptor.SimpleField">
            <interceptor-ref name="ovalValidation">
                <param name="programmatic">false</param>
            </interceptor-ref>
            <result type="void"></result>
        </action>
        <action name="modelDrivenAction" class="org.apache.struts2.oval.interceptor.ModelDrivenAction">
            <interceptor-ref name="ovalValidation">
              <param name="validateJPAAnnotations">true</param>
            </interceptor-ref>
            <result type="void"></result>
        </action>
        <action name="memberObject" class="org.apache.struts2.oval.interceptor.MemberObject">
            <interceptor-ref name="ovalValidation">
              <param name="validateJPAAnnotations">true</param>
            </interceptor-ref>
            <result type="void"></result>
        </action>
    </package>
</xwork>

=== apache/struts/core/src/test/resources/xwork-proxyinvoke.xml
<!DOCTYPE xwork PUBLIC
        "-//Apache Struts//XWork 2.0//EN"
        "http://struts.apache.org/dtds/xwork-2.0.dtd">

<xwork>
    <bean type="com.opensymphony.xwork2.ObjectFactory" name="default" class="com.opensymphony.xwork2.ProxyObjectFactory" />

 	<bean type="com.opensymphony.xwork2.ActionProxyFactory" name="default" class="com.opensymphony.xwork2.DefaultActionProxyFactory"/>
	<constant name="devMode" value="false" />

    <package name="xwork-test-default">
        <result-types>
            <result-type name="chain" class="com.opensymphony.xwork2.ActionChainResult" default="true"/>
            <result-type name="void" class="com.opensymphony.xwork2.VoidResult"/>
            <result-type name="mock" class="com.opensymphony.xwork2.mock.MockResult"/>
        </result-types>

        <interceptors>
            <interceptor name="timer" class="com.opensymphony.xwork2.interceptor.TimerInterceptor"/>
            <interceptor name="logger" class="com.opensymphony.xwork2.interceptor.LoggingInterceptor"/>
            <interceptor name="chain" class="com.opensymphony.xwork2.interceptor.ChainingInterceptor"/>
            <interceptor name="params" class="com.opensymphony.xwork2.interceptor.ParametersInterceptor"/>
            <interceptor name="staticParams" class="com.opensymphony.xwork2.interceptor.StaticParametersInterceptor"/>
            <interceptor name="modelDriven" class="com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor"/>
            <interceptor name="validation" class="com.opensymphony.xwork2.validator.ValidationInterceptor"/>
			<interceptor name="alias" class="com.opensymphony.xwork2.interceptor.AliasInterceptor"/>
            <interceptor name="test" class="com.opensymphony.xwork2.mock.MockInterceptor">
                <param name="foo">expectedFoo</param>
            </interceptor>

            <interceptor-stack name="defaultStack">
                <interceptor-ref name="staticParams"/>
                <interceptor-ref name="modelDriven"/>
                <interceptor-ref name="params"/>
            </interceptor-stack>

            <interceptor-stack name="debugStack">
                <interceptor-ref name="timer"/>
                <interceptor-ref name="logger"/>
            </interceptor-stack>
        </interceptors>
    </package>

    <package name="default" extends="xwork-test-default">

        <action name="ProxyInvocation" method="show" class="com.opensymphony.xwork2.ProxyInvocationAction"/>
    </package>
</xwork>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-interceptor-stack-param-overriding.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xwork PUBLIC
    "-//Apache Struts//XWork 2.0//EN"
    "http://struts.apache.org/dtds/xwork-2.0.dtd">

<xwork>
	<package name="packageOne">
		<result-types>
			<result-type name="mock" class="com.opensymphony.xwork2.mock.MockResult" />
		</result-types>

		<interceptors>
			<interceptor name="interceptorOne" class="com.opensymphony.xwork2.config.providers.InterceptorForTestPurpose" />
			<interceptor name="interceptorTwo" class="com.opensymphony.xwork2.config.providers.InterceptorForTestPurpose" />
			<interceptor name="interceptorThree" class="com.opensymphony.xwork2.config.providers.InterceptorForTestPurpose" />

			<interceptor-stack name="stackOne">
				<interceptor-ref name="interceptorOne" />
				<interceptor-ref name="interceptorTwo" />
				<interceptor-ref name="interceptorThree" />
			</interceptor-stack>

			<interceptor-stack name="stackTwo">
				<interceptor-ref name="stackOne" />
			</interceptor-stack>

			<interceptor-stack name="stackThree">
				<interceptor-ref name="stackTwo" />
			</interceptor-stack>

		</interceptors>

		<action name="actionOne">
			<interceptor-ref name="stackTwo">
				<param name="stackOne.interceptorOne.paramOne">i1p1</param>
				<param name="stackOne.interceptorOne.paramTwo">i1p2</param>
				<param name="stackOne.interceptorTwo.paramOne">i2p1</param>
			</interceptor-ref>
			<result name="success" type="mock">test1</result>
		</action>

		<action name="actionTwo">
			<interceptor-ref name="stackThree">
				<param name="stackTwo.stackOne.interceptorThree.paramOne">i3p1</param>
				<param name="stackTwo.stackOne.interceptorThree.paramTwo">i3p2</param>
				<param name="stackTwo.stackOne.interceptorTwo.paramTwo">i2p2</param>
			</interceptor-ref>
			<result name="success" type="mock">test2</result>
		</action>
	</package>
</xwork>

=== apache/struts/core/src/test/resources/xwork-test-validation.xml
<!DOCTYPE xwork PUBLIC
    "-//Apache Struts//XWork 2.0//EN"
    "http://struts.apache.org/dtds/xwork-2.0.dtd"
 >

<xwork>
	<include file="xwork-test-beans.xml" />
    <package name="xwork-test-default">
        <result-types>
            <result-type name="chain" class="com.opensymphony.xwork2.ActionChainResult" default="true"/>
            <result-type name="void" class="com.opensymphony.xwork2.VoidResult"/>
            <result-type name="mock" class="com.opensymphony.xwork2.mock.MockResult"/>
        </result-types>

        <interceptors>
            <interceptor name="timer" class="com.opensymphony.xwork2.interceptor.TimerInterceptor"/>
            <interceptor name="logger" class="com.opensymphony.xwork2.interceptor.LoggingInterceptor"/>
            <interceptor name="chain" class="com.opensymphony.xwork2.interceptor.ChainingInterceptor"/>
            <interceptor name="params" class="com.opensymphony.xwork2.interceptor.ParametersInterceptor"/>
            <interceptor name="staticParams" class="com.opensymphony.xwork2.interceptor.StaticParametersInterceptor"/>
            <interceptor name="modelDriven" class="com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor"/>
            <interceptor name="validation" class="com.opensymphony.xwork2.validator.ValidationInterceptor">
                <param name="validateAnnotatedMethodOnly">true</param>
            </interceptor>
			<interceptor name="alias" class="com.opensymphony.xwork2.interceptor.AliasInterceptor"/>
            <interceptor name="test" class="com.opensymphony.xwork2.mock.MockInterceptor">
                <param name="foo">expectedFoo</param>
            </interceptor>

            <interceptor-stack name="defaultStack">
                <interceptor-ref name="staticParams"/>
                <interceptor-ref name="modelDriven"/>
                <interceptor-ref name="params"/>
            </interceptor-stack>

            <interceptor-stack name="debugStack">
                <interceptor-ref name="timer"/>
                <interceptor-ref name="logger"/>
            </interceptor-stack>

            <interceptor-stack name="validationStack">
                <interceptor-ref name="staticParams"/>
                <interceptor-ref name="modelDriven"/>
                <interceptor-ref name="params"/>
                <interceptor-ref name="validation"/>
            </interceptor-stack>
        </interceptors>

    </package>
    <package name="default" extends="xwork-test-default">

        <action name="annotatedMethod" class="com.opensymphony.xwork2.test.annotations.ValidateAnnotatedMethodOnlyAction" method="annotatedMethod">
            <interceptor-ref name="validationStack"/>
            <result name="success" type="mock"/>
        </action>
        
        <action name="notAnnotatedMethod" class="com.opensymphony.xwork2.test.annotations.ValidateAnnotatedMethodOnlyAction" method="notAnnotatedMethod">
            <interceptor-ref name="validationStack"/>
            <result name="success" type="mock"/>
        </action>

    </package>

</xwork>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-actions-packagedefaultclassref.xml
<!DOCTYPE xwork PUBLIC
    "-//Apache Struts//XWork 2.0//EN"
    "http://struts.apache.org/dtds/xwork-2.0.dtd"
 >

<xwork>
    <package name="default">

        <result-types>
            <result-type name="chain" class="com.opensymphony.xwork2.ActionChainResult" default="true"/>
            <result-type name="mock" class="com.opensymphony.xwork2.mock.MockResult"/>
        </result-types>

        <interceptors>
            <interceptor name="timer" class="com.opensymphony.xwork2.interceptor.TimerInterceptor"/>
            <interceptor name="logging" class="com.opensymphony.xwork2.interceptor.LoggingInterceptor"/>
            <interceptor name="test" class="com.opensymphony.xwork2.mock.MockInterceptor">
                <param name="foo">fooDefault</param>
            </interceptor>

            <interceptor-stack name="defaultStack">
                <interceptor-ref name="timer"/>
            </interceptor-stack>
        </interceptors>

		<default-class-ref class="com.opensymphony.xwork2.UserSpecifiedDefaultAction" />

        <global-results>
            <result name="login"> <!-- should be chain type since it is the default -->
                <param name="actionName">login</param>
            </result>
        </global-results>

		<!--  No class spcified for action. This should use the default-class-ref -->
        <action name="Bar">
            <param name="foo">17</param>
            <param name="bar">23</param>
            <param name="testForXW171"></param>
        </action>
    </package>
</xwork>
