=== apache/struts/core/src/main/resources/xwork-validator-1.0.3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
-->
<!--
  XWork Validators DTD.
  Used the following DOCTYPE.

  <!DOCTYPE validators PUBLIC
  		"-//Apache Struts//XWork Validator 1.0.3//EN"
  		"http://struts.apache.org/dtds/xwork-validator-1.0.3.dtd">
-->


<!ELEMENT validators (field|validator)+>

<!ELEMENT field (field-validator+)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT field-validator (param*, message)>
<!ATTLIST field-validator
	type CDATA #REQUIRED
    short-circuit (true|false) "false"
>

<!ELEMENT validator (param*, message)>
<!ATTLIST validator
	type CDATA #REQUIRED
    short-circuit (true|false) "false"
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #REQUIRED
>

<!ELEMENT message (#PCDATA|param)*>
<!ATTLIST message
    key CDATA #IMPLIED
>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/validator/validator-parser-test6.xml
<!DOCTYPE validators PUBLIC
        "-//Apache Struts//XWork Validator 1.0.3//EN"
        "http://struts.apache.org/dtds/xwork-validator-1.0.3.dtd">

<validators>
    <field name="name">
        <field-validator type="requiredstring">
            <message key="error.name">default message 1</message>
        </field-validator>
    </field>
    <field name="address">
        <field-validator type="requiredstring">
            <param name="trim">true</param>
            <param name="anotherParam">anotherValue</param>
            <message key="error.address">  ddddd
                <param name="1">'tmjee'</param>
                <param name="2">'phil'</param>
                <param name="10">'jimmy'</param>
                <param name="6">'hopkins'</param>
                <param name="defaultMessage">The Default Message</param>
                <param name="someNonsenseKey">Some Nonesense Value</param>
                <param name="3">'rainer'</param>
            </message>
        </field-validator>
    </field>
</validators>
